name: Build All

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.22.0'
    - run: go version
    - name: GoReSym Build
      run: |
        $Env:GOOS='linux'
        go build -o GoReSym_lin
        $Env:GOOS='windows'
        go build -o GoReSym_win.exe
        $Env:GOOS='darwin'
        go build -o GoReSym_mac
    - name: Zip Build
      run: |
        Compress-Archive -DestinationPath GoReSym.zip -LiteralPath ./GoReSym_lin, ./GoReSym_win.exe, ./GoReSym_mac -CompressionLevel Fastest
    - name: Release
      uses: softprops/action-gh-release@v0.1.12
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: GoReSym.zip
